### ISSUE TITLE
Listing type: Google Cloud Platform dashboards

### ISSUE THREAD

**Issue by arindamchoudhury** [googleapis/python-monitoring-dashboards#85]
DashboardsServiceClient list_dashboards only lists type:custom dashboards.

How to list type: Google Cloud Platform dashboards?

**Comment by busunkim96** [comment]
Hi @arindamchoudhury,

I'm not too familiar with this API, but it looks like it is written to help you [manage custom dashboards](https://cloud.google.com/monitoring/dashboards). The predefined dashboards cannot be changed as far as I can tell.
